# Generated by Django 5.1.4 on 2025-01-21 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_file_alter_message_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='users_online',
            field=models.ManyToManyField(blank=True, related_name='online_in_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
