# Generated by Django 5.1.4 on 2025-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_users_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
