# Generated by Django 5.1.4 on 2025-01-14 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_friend_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friend_requests',
            new_name='received_friend_requests',
        ),
        migrations.AddField(
            model_name='user',
            name='sent_friend_requests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
