# Generated by Django 5.1.4 on 2025-01-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_friend_requests_user_received_friend_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='received_friend_requests',
            new_name='friend_requests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sent_friend_requests',
        ),
    ]
